[package]
name = "tokio-tungstenite"
description = "Tokio binding for Tungstenite, the Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming", "asynchronous", "concurrency"]
keywords = ["websocket", "io", "web"]
authors = ["Daniel Abramov <dabramov@snapview.de>", "Alexey Galakhov <agalakhov@snapview.de>"]
license = "MIT"
homepage = "https://github.com/snapview/tokio-tungstenite"
documentation = "https://docs.rs/tokio-tungstenite/0.10.1"
repository = "https://github.com/snapview/tokio-tungstenite"
version = "0.10.1"
edition = "2018"

[features]
default = ["connect"]
connect = ["stream", "tokio/net"]
tls = ["native-tls", "tokio-tls", "stream", "tungstenite/tls"]
stream = []
deflate = ["tungstenite/deflate"]

[dependencies]
log = "0.4"
futures = "0.3"
pin-project = "0.4"
tokio = { version = "0.2", default-features = false, features = ["io-util"] }

[dependencies.tungstenite]
git = "https://github.com/swimos/tungstenite-rs"
branch = "deflate"
version = "0.11.1"
default-features = false

[dependencies.native-tls]
optional = true
version = "0.2.0"

[dependencies.tokio-tls]
optional = true
version = "0.3"

[dev-dependencies]
tokio = { version = "0.2", default-features = false, features = ["io-std", "macros"] }
url = "2.0.0"
env_logger = "0.7"
